/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelmain;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


public class EmployeeSystem2 extends javax.swing.JFrame {


    public EmployeeSystem2() {
        initComponents();
        DefaultTableModel model = (DefaultTableModel) tableRoom.getModel();
                for(int j=0;j<EmployeeData.employeeList.size();j++){
                    Object[] adds = {EmployeeData.employeeList.get(j).getEmployee(),EmployeeData.employeeList.get(j).getName(),EmployeeData.employeeList.get(j).getSurname(),EmployeeData.employeeList.get(j).getID(),EmployeeData.employeeList.get(j).getPhoneNumber(),String.valueOf(EmployeeData.employeeList.get(j).getsalary())};
                model.addRow(adds);               
              
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRoom = new javax.swing.JTable();
        txtMessage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Add New Employee");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 405, 163, 45));

        jButton2.setText("Delete Employee");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 405, 164, 45));

        jButton3.setText("Edit Employee");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 405, 163, 45));

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1074, 405, 161, 45));

        tableRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee", "Name", "Surname", "ID", "Phone Number", "Salary"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableRoom);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 990, 357));
        getContentPane().add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 377, 516, 21));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmain/back.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableRoom.getModel();
        int selectedRow = tableRoom.getSelectedRow();
                if (selectedRow == -1) {
            if (tableRoom.getRowCount() == 0) {
                txtMessage.setText("The product table is alredy empty.");
            } else {
                txtMessage.setText("Please select a product to delete.");
            }
            
        } else {
                String str = model.getValueAt(tableRoom.getSelectedRow(), 3).toString();
            try {
                EmployeeData.deleteEmployee(EmployeeData.findEmployeeWithID(str));
                txtMessage.setText("Employee Deleted Succesfully");
            } catch (IOException ex) {
                Logger.getLogger(EmployeeSystem2.class.getName()).log(Level.SEVERE, null, ex);
            }
             
             
         /*try {
             Data.removeRoomWithNumber(no);
         } catch (IOException ex) {
             Logger.getLogger(managementSystem.class.getName()).log(Level.SEVERE, null, ex);
         }*/
        model.removeRow(selectedRow);
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AddEmployee ae = new AddEmployee();
        ae.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                DefaultTableModel model = (DefaultTableModel) tableRoom.getModel();
                
        int selectedRow = tableRoom.getSelectedRow();
            if (selectedRow == -1) {
            if (tableRoom.getRowCount() == 0) {
                txtMessage.setText("The product table is alredy empty.");
            } else {
                txtMessage.setText("Please select a product to delete.");
            }}
            else{
                    String str = model.getValueAt(tableRoom.getSelectedRow(), 0).toString();
                    String id = model.getValueAt(tableRoom.getSelectedRow(),3).toString();
                    Employee e = EmployeeData.findEmployeeWithID(id);
                    EditEmployee ee = new EditEmployee(e);
                    ee.setVisible(true);
                    this.setVisible(false);
                   }
        
        
                
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        managementSystem ms = new managementSystem();
        ms.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeSystem2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeSystem2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeSystem2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeSystem2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeSystem2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableRoom;
    private javax.swing.JLabel txtMessage;
    // End of variables declaration//GEN-END:variables
}
